### ISSUE TITLE
Supported Extensions

### ISSUE THREAD

**Issue by prionkor** [ItsAsbreuk/itsa-react-docviewer#4]
What are the list of file types that docviewer supports?

**Comment by ItsAsbreuk** [comment]
Because the module relies on Google Docs Viewer, it supports those formats:

* Adobe PDF (.PDF)
* Microsoft Word (.DOC and .DOCX)
* Microsoft Excel (.XLS and .XLSX)
* Microsoft PowerPoint (PPT, .PPTX)
* Apple Pages (.PAGES)
* Adobe Illustrator (.AI)
* Adobe Photoshop (.PSD)
* Autodesk AutoCad (.DXF)
* Scalable Vector Graphics (.SVG)
* PostScript (.EPS, .PS)
* TrueType (.TTF)
* XML Paper Specification (.XPS)
* Tagged Image File Format (.TIF, .TIFF)
* Archive file types (.ZIP and .RAR)
* Text and Markup/COde (.TXT, .CSS, .HTML, .PHP, .C, .CPP, .H, .HPP, .JS)
